### ISSUE TITLE
Complete the github pages

### ISSUE THREAD

**Issue by WashingtonBispo** [Interacao-Humano-Computador/2020.1-UVaJudge#10]
## Description

There are still a few documents without content

## Tasks
* Complete the following documents

- [x] ferramentas.md
- [x] porque_uva.md
- [x] processo_design.md
- [x] avaliacao_uva.md
- [x] avaliacao_poupatemposp.md
