### ISSUE TITLE
Research our user profile

### ISSUE THREAD

**Issue by WashingtonBispo** [Interacao-Humano-Computador/2020.1-UVaJudge#12]
# Description
We need to define what kind type of person use the website we are working.

# Tasks
- [ ] Define some groups
- [ ] Define which would use the website
- [ ] Create a list of types that will be used to create our personas
