### ISSUE TITLE
Create meeting minutes

### ISSUE THREAD

**Issue by SergioAlmeidaCiprianoJr** [Interacao-Humano-Computador/2020.1-UVaJudge#16]
## Description

We already had 2 meetings, we need to organize the minutes.

# Tasks

- [ ] Write meeting minutes
- [ ] Put them on the wiki or website, wherever it looks best
- [ ] The same goes for meetings with the professor
